import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NGO Eureka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased sm:mx-6 md:mx-12 lg:mx-20`}
      >
        <div className="">
            <div className="max-w-screen-2.5xl 2.5xl:mx-auto mx-4">
              <Header />
            </div>
        </div>
        <div className="max-w-screen-2.5xl 2.5xl:mx-auto  sm:mx-4 overflow-x-hidden sm:overflow-x-visible overflow-y-visible scroll-smooth">
          {children}
        </div>
      </body>
    </html>
  );
}
